name: Backend Deployment

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  DevDeployment:
    name: Dev Deployment
    runs-on: test
    environment:
      name: Development
    steps:
      - name: Deploy
        run: |
            echo "PR Merged: ${{ github.event.pull_request.merged }}"
            echo "Base Ref: ${{ github.event.pull_request.base.ref }}"
            echo "Head Ref: ${{ github.event.pull_request.head.ref }}"
            PR_NUMBER=${{ github.event.pull_request.number }}
            SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}
            echo "PR Number: $PR_NUMBER"
            echo "Source Branch: $SOURCE_BRANCH"
            printenv
            echo DevDeployment! 


  StagingDeployment:
    name: Staging Deployment
    if: github.event.pull_request.merged == 'true' && github.event.pull_request.base.ref == 'master'
    needs: [DevDeployment]
    runs-on: test
    environment:
      name: Staging
    steps:
      - name: Deploy
        run: echo StagingDeployment!

  ProdDeployment:
    name: Production Deployment
    if: github.event.pull_request.merged == 'true' && github.event.pull_request.base.ref == 'master'
    needs: [StagingDeployment]
    runs-on: test
    environment:
      name: Production
    steps:
      - name: Deploy
        run: echo ProdDeployment!

  CreateReleaseTag:
    name: Create Release Tag
    if: github.event.pull_request.merged == 'true' && github.event.pull_request.base.ref == 'master'
    needs: [ProdDeployment]
    runs-on: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Release Tag (e.g., v1.0.0)
        id: vars
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.vars.outputs.tag_name }}
          git push origin ${{ steps.vars.outputs.tag_name }}