name: Backend Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
    
  DevDeployment:
    name: Dev Deployment
    if: github.event.ref == 'refs/heads/main'
    runs-on: test
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: echo DevDeployment! 
    
  StagingDeployment:
    name: Staging Deployment
    if: github.event.ref == 'refs/heads/main'
    needs: [DevDeployment]
    runs-on: test
    environment: 
      name: Staging
    steps:
      - name: Deploy
        run: echo StagingDeployment! 
            
  ProdDeployment:
    name: Production Deployment
    if: github.event.ref == 'refs/heads/main'
    needs: [StagingDeployment]
    runs-on: test
    environment: 
      name: Production
    steps:
      - name: Deploy
        run: echo ProdDeployment! 
    